AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Content Analysis Workflow - Workflow to run video analyses"

Parameters:
  WorkflowCustomResourceArn:
    Type: String
    Description: "ARN of the Media Insights custom resource that handles creating operations, stages and workflows"
  OperatorLibraryStack:
    Description: "Name of the MIE operator library stack"
    Type: String

Resources:
  PreliminaryStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "defaultPrelimVideoStage"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:Thumbnail"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:Mediainfo"
  defaultVideoStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "defaultVideoStage"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:CelebRecognition"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:ContentModeration"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:FaceDetection"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:LabelDetection"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:TextDetection"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:TechnicalCueDetection"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:ShotDetection"

  defaultAudioStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "defaultAudioStage"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:TranscribeVideo"

  CasVideoWorkflow:
    DependsOn:
      - PreliminaryStage
      - defaultVideoStage
      - defaultAudioStage
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Workflow"
      Name: "CasVideoWorkflow"
      StartAt: !GetAtt PreliminaryStage.Name
      Stages: !Sub
        - |-
          {
            "${PreliminaryStage}":{
              "Next": "${defaultVideoStage}"
              },
            "${defaultVideoStage}":{
              "Next": "${defaultAudioStage}"
              },
            "${defaultAudioStage}":{
              "End": true
              }
          }
        - {
          PreliminaryStage: !GetAtt PreliminaryStage.Name,
          defaultVideoStage: !GetAtt defaultVideoStage.Name,
          defaultAudioStage: !GetAtt defaultAudioStage.Name
        }
